# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films_api', '0002_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='related_films',
        ),
        migrations.RemoveField(
            model_name='film',
            name='url_slug',
        ),
        migrations.AddField(
            model_name='film',
            name='img_url',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
